# Generated by Django 4.2.7 on 2023-11-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='next_pay_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующего списания'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='iban',
            field=models.CharField(max_length=100, verbose_name='счет списания'),
        ),
    ]
