# Generated by Django 4.2.2 on 2023-09-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.CharField(max_length=11, unique=True, verbose_name='номер телефона'),
        ),
    ]
