# Generated by Django 4.2.7 on 2023-11-17 16:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Number не верный формат', regex='^\\d{16}$')], verbose_name='номер счета')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='баланс счета')),
                ('currency', models.CharField(choices=[('KZT', 'Tenge'), ('RUB', 'Rubli'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='KZT', max_length=4, verbose_name='валюта')),
                ('type', models.CharField(choices=[('Gold', 'Kaspi Gold'), ('Red', 'Kaspi Red'), ('Dep', 'Kaspi Deposit')], default='Gold', max_length=4, verbose_name='тип счета')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='счет', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outamount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='исходящая сумма')),
                ('inamount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='поступившая сумма')),
                ('outcurrency', models.CharField(choices=[('KZT', 'Tenge'), ('RUB', 'Rubli'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='KZT', max_length=4, verbose_name='исходящая валюта')),
                ('incurrency', models.CharField(choices=[('KZT', 'Tenge'), ('RUB', 'Rubli'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='KZT', max_length=4, verbose_name='поступившая валюта')),
                ('outbalance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='остаток на исходящем счете')),
                ('inbalance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='остаток на входящем счете')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer')], default='Transfer', max_length=10, verbose_name='Тип транзакции')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата перевода')),
                ('inaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='bank.bankaccount', verbose_name='счет-отправитель')),
                ('outaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='bank.bankaccount', verbose_name='счет-получатель')),
            ],
            options={
                'verbose_name': 'перевод',
                'verbose_name_plural': 'переводы',
                'ordering': ('-pk',),
            },
        ),
    ]
