# Generated by Django 4.2.7 on 2023-11-09 15:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Number не верный формат', regex='^\\d{16}$')], verbose_name='номер счета')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='баланс счета')),
                ('currency', models.CharField(choices=[('KZT', 'Tenge'), ('RUB', 'Rubli'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='KZT', max_length=4, verbose_name='валюта')),
                ('type', models.CharField(choices=[('Gold', 'Kaspi Gold'), ('Red', 'Kaspi Red'), ('Dep', 'Deposit')], default='Gold', max_length=4, verbose_name='тип счета')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='счет', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
