# Generated by Django 4.2.7 on 2023-12-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Снятие'), ('Transfer', 'Перевод'), ('Inst', 'Рассрочка')], default='Transfer', max_length=10, verbose_name='Тип транзакции'),
        ),
    ]
