# Generated by Django 4.2.7 on 2023-11-09 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Number не верный формат', regex='^\\d{16}$')], verbose_name='номер счета'),
        ),
    ]
