# Generated by Django 4.2.7 on 2023-11-12 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0003_alter_bankaccount_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='баланс счета')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('inaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_transfers', to='bank.bankaccount')),
                ('outaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_transfers', to='bank.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
