# Generated by Django 4.2.7 on 2023-11-12 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0005_alter_transfer_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('-pk',), 'verbose_name': 'перевод', 'verbose_name_plural': 'переводы'},
        ),
        migrations.AlterField(
            model_name='transfer',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата перевода'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='inaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_transfers', to='bank.bankaccount', verbose_name='входящий счет'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='outaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_transfers', to='bank.bankaccount', verbose_name='исходящий счет'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель'),
        ),
    ]
