# Generated by Django 4.2.7 on 2023-11-13 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_transfer_options_alter_transfer_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='user',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer')], default='Transfer', max_length=10, verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='type',
            field=models.CharField(choices=[('Gold', 'Kaspi Gold'), ('Red', 'Kaspi Red'), ('Dep', 'Kaspi Deposit')], default='Gold', max_length=4, verbose_name='тип счета'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='inaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='bank.bankaccount', verbose_name='счет-отправитель'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='outaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='bank.bankaccount', verbose_name='счет-получатель'),
        ),
    ]
