# Generated by Django 4.2.7 on 2023-11-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_remove_transfer_user_transfer_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=333, max_digits=10, verbose_name='остаток на счете'),
            preserve_default=False,
        ),
    ]
