# Generated by Django 4.2.5 on 2023-11-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_transfer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='currency',
            field=models.CharField(choices=[('KZT', 'Tenge'), ('RUB', 'Rubli'), ('EUR', 'Euro'), ('USD', 'Dollar')], default='KZT', max_length=4, verbose_name='валюта'),
        ),
    ]
